- name: use the k8s cluster master role
  hosts: Master
  roles:
    - mtabishk.ansible_kubernetes_master_role 

- name: use the k8s cluster worker role
  hosts: Worker
  roles:
    - mtabishk.ansible_kubernetes_worker_role 
